# Generated by Django 3.1.3 on 2021-05-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dateTime',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
